[project]
name = "varscore"
description = "A library for common functions in variant effect prediction & prioritization."
authors = [
	{ name = "Ivy Evergreen" },
	{ name = "Salil Deshpande" },
	{ name = "Riya Sinha" },
]
version = "0.0.1a"
requires-python = ">= 3.8, < 3.10"
dependencies = [
	"deeplift==0.6.13.0",
	"fastapi>=0.103.2",
	"intervaltree>=3.1.0",
	"logomaker",
	"numpy==1.23.4",
	"pandas>=1.3.4",
	"polars==1.8.2",
	"protobuf<=3.20",
	"pybedtools==0.10.0",
	"pyfaidx==0.6.1",
	"kundajelab-shap==1",
	"scipy==1.10.1",
	# "tangermeme>=0.4.0",
	"tensorflow==2.8.1",
	"tensorflow-probability==0.14.0",
	# "tf-keras>=2.15.0",
	"uvicorn>=0.33.0",
	"python-snappy>=0.7.3",
	"pyarrow>=17.0.0",
	"pybigwig>=0.3.22",
	"pysam>=0.22.1",
]
keywords = ["variant scoring", "variant effect", "variant prioritization", "variant", "scoring", "effect", "prioritization", "genomics", "chrombpnet"]

[project.urls]
Repository = "https://github.com/kundajelab/varscore.git"
Issues = "https://github.com/kundajelab/varscore/issues"

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "varscore" }

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
